import 'package:flutter/material.dart';

enum CharacterHairStyle {
  messy,
  visor,
  longHair,
  bun,
  cropped,
  swept,
  braided,
  wavy,
  tied,
}

enum CharacterClothing {
  jacket,
  hoodie,
  collar,
  utility,
  layered,
}

enum CharacterAccessory {
  headphones,
  orb,
  badge,
  notebook,
  glasses,
  star,
  slate,
  tool,
  question,
  book,
  link,
  compass,
  scanner,
  none,
}

enum CharacterMotion { subtle, attentive, analytical, adaptive, energetic }

/// Canonical visual identity for the complete 15-specialist roster.
///
/// The supplied Criterivox roster reference is treated as visual direction only:
/// palette, silhouette cues, hair, clothing language and signature objects are
/// encoded here as procedural/vector properties. No artwork or raster asset is
/// required at runtime.
class CharacterVisualProfile {
  final String characterId;
  final Color skin;
  final Color face;
  final Color body;
  final Color trousers;
  final Color hair;
  final Color accent;
  final Color dark;
  final CharacterHairStyle hairStyle;
  final CharacterClothing clothing;
  final CharacterAccessory accessory;
  final CharacterMotion idleMotion;
  final CharacterMotion workMotion;

  const CharacterVisualProfile({
    required this.characterId,
    required this.skin,
    required this.face,
    required this.body,
    required this.trousers,
    required this.hair,
    required this.accent,
    required this.dark,
    required this.hairStyle,
    required this.clothing,
    required this.accessory,
    required this.idleMotion,
    required this.workMotion,
  });

  static const Map<String, CharacterVisualProfile> registry = {
    'dharen': CharacterVisualProfile(
      characterId: 'dharen',
      skin: Color(0xffc98964),
      face: Color(0xffffd7bc),
      body: Color(0xff8b5e3c),
      trousers: Color(0xff403d46),
      hair: Color(0xff34251f),
      accent: Color(0xffd98b43),
      dark: Color(0xff201b1a),
      hairStyle: CharacterHairStyle.messy,
      clothing: CharacterClothing.jacket,
      accessory: CharacterAccessory.notebook,
      idleMotion: CharacterMotion.analytical,
      workMotion: CharacterMotion.analytical,
    ),
    'vivren': CharacterVisualProfile(
      characterId: 'vivren',
      skin: Color(0xffc7957e),
      face: Color(0xffffd8c7),
      body: Color(0xffd5d0dc),
      trousers: Color(0xff36333e),
      hair: Color(0xffc8bdd9),
      accent: Color(0xffa68ad7),
      dark: Color(0xff26222d),
      hairStyle: CharacterHairStyle.longHair,
      clothing: CharacterClothing.layered,
      accessory: CharacterAccessory.glasses,
      idleMotion: CharacterMotion.subtle,
      workMotion: CharacterMotion.attentive,
    ),
    'tarkis': CharacterVisualProfile(
      characterId: 'tarkis',
      skin: Color(0xffa96f56),
      face: Color(0xffffcdb6),
      body: Color(0xff34383f),
      trousers: Color(0xff171a1e),
      hair: Color(0xff171719),
      accent: Color(0xffee8b31),
      dark: Color(0xff111214),
      hairStyle: CharacterHairStyle.messy,
      clothing: CharacterClothing.hoodie,
      accessory: CharacterAccessory.star,
      idleMotion: CharacterMotion.analytical,
      workMotion: CharacterMotion.energetic,
    ),
    'sandre': CharacterVisualProfile(
      characterId: 'sandre',
      skin: Color(0xffa96f58),
      face: Color(0xffffcbb5),
      body: Color(0xff496d6d),
      trousers: Color(0xff343f43),
      hair: Color(0xff2d2522),
      accent: Color(0xff63b9a8),
      dark: Color(0xff1d2527),
      hairStyle: CharacterHairStyle.longHair,
      clothing: CharacterClothing.collar,
      accessory: CharacterAccessory.badge,
      idleMotion: CharacterMotion.subtle,
      workMotion: CharacterMotion.attentive,
    ),
    'pramon': CharacterVisualProfile(
      characterId: 'pramon',
      skin: Color(0xffb9785e),
      face: Color(0xffffd2bc),
      body: Color(0xff8f8a7c),
      trousers: Color(0xff2b2d31),
      hair: Color(0xff4a3328),
      accent: Color(0xffe1ad45),
      dark: Color(0xff1b1b1d),
      hairStyle: CharacterHairStyle.swept,
      clothing: CharacterClothing.utility,
      accessory: CharacterAccessory.slate,
      idleMotion: CharacterMotion.analytical,
      workMotion: CharacterMotion.analytical,
    ),
    'syvax': CharacterVisualProfile(
      characterId: 'syvax',
      skin: Color(0xffb87c63),
      face: Color(0xffffd4bd),
      body: Color(0xff344d63),
      trousers: Color(0xff252d36),
      hair: Color(0xff17232e),
      accent: Color(0xff62d8f5),
      dark: Color(0xff14202a),
      hairStyle: CharacterHairStyle.visor,
      clothing: CharacterClothing.hoodie,
      accessory: CharacterAccessory.headphones,
      idleMotion: CharacterMotion.subtle,
      workMotion: CharacterMotion.attentive,
    ),
    'bodhex': CharacterVisualProfile(
      characterId: 'bodhex',
      skin: Color(0xffc18769),
      face: Color(0xffffd9c3),
      body: Color(0xff4d5960),
      trousers: Color(0xff20272d),
      hair: Color(0xff24282b),
      accent: Color(0xffb4d36b),
      dark: Color(0xff14181b),
      hairStyle: CharacterHairStyle.cropped,
      clothing: CharacterClothing.utility,
      accessory: CharacterAccessory.tool,
      idleMotion: CharacterMotion.energetic,
      workMotion: CharacterMotion.energetic,
    ),
    'manis': CharacterVisualProfile(
      characterId: 'manis',
      skin: Color(0xffb87960),
      face: Color(0xffffd0bd),
      body: Color(0xff5f5264),
      trousers: Color(0xff292a35),
      hair: Color(0xff302329),
      accent: Color(0xff78c6a3),
      dark: Color(0xff1d1b22),
      hairStyle: CharacterHairStyle.braided,
      clothing: CharacterClothing.layered,
      accessory: CharacterAccessory.question,
      idleMotion: CharacterMotion.attentive,
      workMotion: CharacterMotion.adaptive,
    ),
    'anuka': CharacterVisualProfile(
      characterId: 'anuka',
      skin: Color(0xffd69a79),
      face: Color(0xffffdfcf),
      body: Color(0xfff0b9c8),
      trousers: Color(0xff343044),
      hair: Color(0xff2a2025),
      accent: Color(0xffbd7fe4),
      dark: Color(0xff221b27),
      hairStyle: CharacterHairStyle.bun,
      clothing: CharacterClothing.hoodie,
      accessory: CharacterAccessory.orb,
      idleMotion: CharacterMotion.adaptive,
      workMotion: CharacterMotion.adaptive,
    ),
    'viveda': CharacterVisualProfile(
      characterId: 'viveda',
      skin: Color(0xffc38b70),
      face: Color(0xffffd8c6),
      body: Color(0xff41607b),
      trousers: Color(0xff262d3a),
      hair: Color(0xff9c725f),
      accent: Color(0xff4fc0d8),
      dark: Color(0xff18212b),
      hairStyle: CharacterHairStyle.wavy,
      clothing: CharacterClothing.layered,
      accessory: CharacterAccessory.book,
      idleMotion: CharacterMotion.subtle,
      workMotion: CharacterMotion.analytical,
    ),
    'kaelen': CharacterVisualProfile(
      characterId: 'kaelen',
      skin: Color(0xffbd805e),
      face: Color(0xffffd1b8),
      body: Color(0xff50575f),
      trousers: Color(0xff20252a),
      hair: Color(0xff1d1b1b),
      accent: Color(0xfff19a3e),
      dark: Color(0xff17191c),
      hairStyle: CharacterHairStyle.messy,
      clothing: CharacterClothing.jacket,
      accessory: CharacterAccessory.headphones,
      idleMotion: CharacterMotion.subtle,
      workMotion: CharacterMotion.energetic,
    ),
    'anukor': CharacterVisualProfile(
      characterId: 'anukor',
      skin: Color(0xffd2a07e),
      face: Color(0xffffe0cb),
      body: Color(0xff7a6171),
      trousers: Color(0xff2d3040),
      hair: Color(0xffcbb8a6),
      accent: Color(0xffc46fe1),
      dark: Color(0xff24202a),
      hairStyle: CharacterHairStyle.tied,
      clothing: CharacterClothing.utility,
      accessory: CharacterAccessory.link,
      idleMotion: CharacterMotion.adaptive,
      workMotion: CharacterMotion.energetic,
    ),
    'medrus': CharacterVisualProfile(
      characterId: 'medrus',
      skin: Color(0xffbd866e),
      face: Color(0xffffd6c2),
      body: Color(0xff70777b),
      trousers: Color(0xff25292d),
      hair: Color(0xff6f5b54),
      accent: Color(0xff70c8a6),
      dark: Color(0xff1b1e20),
      hairStyle: CharacterHairStyle.cropped,
      clothing: CharacterClothing.layered,
      accessory: CharacterAccessory.scanner,
      idleMotion: CharacterMotion.analytical,
      workMotion: CharacterMotion.energetic,
    ),
    'epistre': CharacterVisualProfile(
      characterId: 'epistre',
      skin: Color(0xffd1a087),
      face: Color(0xffffdfce),
      body: Color(0xffc9c4bd),
      trousers: Color(0xff35343a),
      hair: Color(0xffc6b4a2),
      accent: Color(0xffb49a52),
      dark: Color(0xff27252a),
      hairStyle: CharacterHairStyle.longHair,
      clothing: CharacterClothing.layered,
      accessory: CharacterAccessory.compass,
      idleMotion: CharacterMotion.subtle,
      workMotion: CharacterMotion.analytical,
    ),
    'veridat': CharacterVisualProfile(
      characterId: 'veridat',
      skin: Color(0xffc48c73),
      face: Color(0xffffd8c3),
      body: Color(0xffe1ddd3),
      trousers: Color(0xff353941),
      hair: Color(0xff3d302c),
      accent: Color(0xff7bb8df),
      dark: Color(0xff20242a),
      hairStyle: CharacterHairStyle.swept,
      clothing: CharacterClothing.utility,
      accessory: CharacterAccessory.scanner,
      idleMotion: CharacterMotion.analytical,
      workMotion: CharacterMotion.attentive,
    ),
  };

  static CharacterVisualProfile? forId(String id) =>
      registry[id.trim().toLowerCase()];
}
