import 'dart:async'; import 'package:flutter/material.dart'; import '../presentation/runtime_client.dart'; import '../presentation/presentation_state.dart';
class CharacterChatPage extends StatefulWidget{final String characterId;const CharacterChatPage({super.key,required this.characterId});@override State<CharacterChatPage> createState()=>_CharacterChatPageState();}
class _CharacterChatPageState extends State<CharacterChatPage>{
 late final RuntimeClient _runtime;late final StreamSubscription<PresentationState> _sub;final _input=TextEditingController();final _messages=<Map<String,dynamic>>[];
 final _chipsEn=const ['What is happening?','What happens next?','What changed?','Why?','Show provenance','Continue','Pause','Review the plan','Show options','Recommend','Challenge','Verify result'];
final _chipsHi=const ['अभी क्या हो रहा है?','आगे क्या होगा?','क्या बदला?','क्यों?','स्रोत दिखाओ','जारी रखें','रोकें','योजना की समीक्षा करें','विकल्प दिखाओ','सिफारिश करो','चुनौती दो','परिणाम सत्यापित करो'];
final _chipsMr=const ['आत्ता काय चालले आहे?','पुढे काय होईल?','काय बदलले?','का?','स्रोत दाखवा','सुरू ठेवा','थांबवा','योजनेचा आढावा घ्या','पर्याय दाखवा','शिफारस करा','आव्हान द्या','निकाल सत्यापित करा'];
 @override void initState(){super.initState();_runtime=RuntimeClient();_sub=_runtime.states.listen(_onState);_runtime.connect();}
 void _onState(PresentationState s){final m=s.message?.trim();if(m==null||m.isEmpty||s.event=='RUNTIME_CONNECTED')return;if(mounted)setState(()=>_messages.add({'author':s.characterId??widget.characterId,'text':m,'u':s.unified}));}
 Future<void> _send([String? chip])async{final text=(chip??_input.text).trim();if(text.isEmpty)return;_input.clear();setState(()=>_messages.add({'author':'human','text':text}));await _runtime.send(message:text,characterId:widget.characterId);}
 @override void dispose(){_sub.cancel();_input.dispose();_runtime.dispose();super.dispose();}
 @override Widget build(BuildContext c){final u=_runtime.state.unified;return Scaffold(appBar:AppBar(title:Text('${widget.characterId} · Character Chat'),actions:[Padding(padding:const EdgeInsets.all(12),child:Center(child:Text(_runtime.connected?'CONNECTED':'OFFLINE')))]),body:Column(children:[
 Padding(padding:const EdgeInsets.fromLTRB(12,12,12,4),child:Row(children:[ClipRRect(borderRadius:BorderRadius.circular(14),child:Image.asset('assets/characters/portraits/${widget.characterId.toLowerCase()}.webp',width:76,height:92,fit:BoxFit.cover,errorBuilder:(context,error,stack)=>const SizedBox(width:76,height:92,child:Icon(Icons.person_outline,size:42)))),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(widget.characterId,style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const SizedBox(height:4),const Text('Hero identity portrait',style:TextStyle(fontSize:12))]))])),
 Expanded(child:ListView.builder(itemCount:_messages.length,itemBuilder:(_,i){final m=_messages[i];final x=m['u'];return Card(margin:const EdgeInsets.all(8),child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(m['author'] as String,style:const TextStyle(fontWeight:FontWeight.bold)),const SizedBox(height:5),Text(m['text'] as String),if(x!=null)Wrap(spacing:5,children:[if(x.intent!=null)Chip(label:Text('Intent: '+x.intent)),if(x.capability!=null)Chip(label:Text('Capability: '+x.capability)),if(x.responsibleCharacter!=null)Chip(label:Text('Owner: '+x.responsibleCharacter)),if(x.authorization!=null)Chip(label:Text('Auth: '+x.authorization)),if(x.stateSource!=null)Chip(label:Text('State: '+x.stateSource)),if(x.status!=null)Chip(label:Text(x.status!))])])));}),),
 SizedBox(height:52,child:ListView(scrollDirection:Axis.horizontal,padding:const EdgeInsets.all(8),children:(_runtime.state.unified?.responseLanguage=='hi'? _chipsHi : _runtime.state.unified?.responseLanguage=='mr' ? _chipsMr : _chipsEn).map((x)=>Padding(padding:const EdgeInsets.only(right:6),child:ActionChip(label:Text(x),onPressed:()=>_send(x)))).toList())),
 Padding(padding:const EdgeInsets.all(10),child:Row(children:[Expanded(child:TextField(controller:_input,onSubmitted:(_)=>_send(),decoration:const InputDecoration(border:OutlineInputBorder(),hintText:'Ask the runtime...'))),IconButton(onPressed:_send,icon:const Icon(Icons.send))])),
 if(u?.status=='CAPABILITY_UNAVAILABLE')const Text('Capability unavailable. No unsupported operation was executed.')
 ]));}
}