import 'dart:convert';
import '../character/character_identity.dart';

class PresentationState {
  static const allowedStates = <String>{'IDLE','RECEIVE','WORK','COMMUNICATE','HANDOFF','COMPLETE','WARNING'};
  final String agentId; final String characterState; final bool active; final bool reducedMotion; final double? prominence; final String? message; final String? event;
  final String? taskId; final String? taskState; final String? taskSource; final String? task; final int? taskDataFields; final int? taskContextFields; final String? taskCreatedAt; final String? taskUpdatedAt;
  final String? foundationId; final String? foundationMaterialSetId; final int? foundationSourceCount; final int? foundationCandidateCount; final String? foundationConfirmation; final String? foundationPreviewQuestion; final double? foundationMatchRatio; final bool? foundationAutoFill; final List<String> foundationIntentGuesses; final String? foundationRecipient; final int? foundationLogCount; final List<String> foundationLogEntries; final List<String> foundationConflictFields; final List<String> foundationConditionalProvenance; final Map<String,dynamic>? s5FeaturePayload;
  final String? executionEngine; final String? executionTier; final bool? fallbackUsed;
  final String? doorAddress; final Map<String,dynamic>? lineageSnapshot; final String? coordinationId; final List<String> coordinationMembers; final String? deliveryId; final String? deliveryRecipient; final String? deliveryStatus;
  final List<Map<String,dynamic>> observations; final List<Map<String,dynamic>> findings; final List<Map<String,dynamic>> evidence; final List<String> activity; final String? error;
  const PresentationState({required this.agentId,required this.characterState,required this.active,this.reducedMotion=false,this.prominence,this.message,this.event,this.taskId,this.taskState,this.taskSource,this.task,this.taskDataFields,this.taskContextFields,this.taskCreatedAt,this.taskUpdatedAt,this.foundationId,this.foundationMaterialSetId,this.foundationSourceCount,this.foundationCandidateCount,this.foundationConfirmation,this.foundationPreviewQuestion,this.foundationMatchRatio,this.foundationAutoFill,this.foundationIntentGuesses=const [],this.foundationRecipient,this.foundationLogCount,this.foundationLogEntries=const [],this.foundationConflictFields=const [],this.foundationConditionalProvenance=const [],this.s5FeaturePayload,this.executionEngine,this.executionTier,this.fallbackUsed,this.doorAddress,this.lineageSnapshot,this.coordinationId,this.coordinationMembers=const [],this.deliveryId,this.deliveryRecipient,this.deliveryStatus,this.observations=const [],this.findings=const [],this.evidence=const [],this.activity=const [],this.error});
  factory PresentationState.fromJson(String raw){
    final decoded=jsonDecode(raw); if(decoded is! Map<String,dynamic>) throw const FormatException('Runtime message must be an object.');
    if(decoded['contract_version']!=1) throw const FormatException('Unsupported presentation contract version.');
    final agentId=decoded['character_id']; final stateValue=decoded['character_state']; final active=decoded['active']; final prominence=decoded['prominence'];
    if(agentId is! String || agentId.trim().isEmpty || !CharacterIdentities.all.containsKey(agentId)) throw const FormatException('Runtime message has an unknown character.');
    if(stateValue is! String || !allowedStates.contains(stateValue.toUpperCase())) throw const FormatException('Runtime message has an unsupported state.');
    if(active is! bool || prominence is! num || prominence<0 || prominence>1) throw const FormatException('Runtime message has invalid character state.');
    final message=decoded['message']; final event=decoded['event']; if(message!=null && message is! String) throw const FormatException('Runtime message has invalid message.'); if(event!=null && event is! String) throw const FormatException('Runtime message has invalid event.');
    List<Map<String,dynamic>> maps(dynamic value)=>value is List?value.whereType<Map>().map((x)=>Map<String,dynamic>.from(x)).toList():const [];
    List<String> strings(dynamic value)=>value is List?value.whereType<String>().toList():const [];
    int? integer(dynamic value)=>value is num?value.toInt():null; String? optionalString(dynamic value)=>value is String?value:null; bool? optionalBool(dynamic value)=>value is bool?value:null; double? decimal(dynamic value)=>value is num?value.toDouble():null; Map<String,dynamic>? object(dynamic value)=>value is Map?Map<String,dynamic>.from(value):null;
    return PresentationState(agentId:agentId,characterState:stateValue.toUpperCase(),active:active,reducedMotion:decoded['reduced_motion']==true,prominence:prominence.toDouble(),message:message as String?,event:event as String?,taskId:optionalString(decoded['task_id']),taskState:optionalString(decoded['task_state']),taskSource:optionalString(decoded['task_source']),task:optionalString(decoded['task']),taskDataFields:integer(decoded['task_data_fields']),taskContextFields:integer(decoded['task_context_fields']),taskCreatedAt:optionalString(decoded['task_created_at']),taskUpdatedAt:optionalString(decoded['task_updated_at']),foundationId:optionalString(decoded['foundation_id']),foundationMaterialSetId:optionalString(decoded['foundation_material_set_id']),foundationSourceCount:integer(decoded['foundation_source_count']),foundationCandidateCount:integer(decoded['foundation_candidate_count']),foundationConfirmation:optionalString(decoded['foundation_confirmation']),foundationPreviewQuestion:optionalString(decoded['foundation_preview_question']),foundationMatchRatio:decimal(decoded['foundation_match_ratio']),foundationAutoFill:optionalBool(decoded['foundation_auto_fill']),foundationIntentGuesses:strings(decoded['foundation_intent_guesses']),foundationRecipient:optionalString(decoded['foundation_recipient']),foundationLogCount:integer(decoded['foundation_log_count']),foundationLogEntries:strings(decoded['foundation_log_entries']),foundationConflictFields:strings(decoded['foundation_conflict_fields']),foundationConditionalProvenance:strings(decoded['foundation_conditional_provenance']),s5FeaturePayload:object(decoded['s5_feature_payload']),executionEngine:optionalString(decoded['execution_engine']),executionTier:optionalString(decoded['execution_tier']),fallbackUsed:optionalBool(decoded['fallback_used']),doorAddress:optionalString(decoded['door_address']),lineageSnapshot:object(decoded['lineage_snapshot']),coordinationId:optionalString(decoded['coordination_id']),coordinationMembers:strings(decoded['coordination_members']),deliveryId:optionalString(decoded['delivery_id']),deliveryRecipient:optionalString(decoded['delivery_recipient']),deliveryStatus:optionalString(decoded['delivery_status']),observations:maps(decoded['observations']),findings:maps(decoded['findings']),evidence:maps(decoded['evidence']),activity:strings(decoded['activity']),error:optionalString(decoded['error']));
  }
  Map<String,dynamic> toJson()=>{'contract_version':1,'character_id':agentId,'character_state':characterState,'active':active,'reduced_motion':reducedMotion,'prominence':prominence,'message':message,'event':event,'task_id':taskId,'task_state':taskState,'task_source':taskSource,'task':task,'task_data_fields':taskDataFields,'task_context_fields':taskContextFields,'task_created_at':taskCreatedAt,'task_updated_at':taskUpdatedAt,'foundation_id':foundationId,'foundation_material_set_id':foundationMaterialSetId,'foundation_source_count':foundationSourceCount,'foundation_candidate_count':foundationCandidateCount,'foundation_confirmation':foundationConfirmation,'foundation_preview_question':foundationPreviewQuestion,'foundation_match_ratio':foundationMatchRatio,'foundation_auto_fill':foundationAutoFill,'foundation_intent_guesses':foundationIntentGuesses,'foundation_recipient':foundationRecipient,'foundation_log_count':foundationLogCount,'foundation_log_entries':foundationLogEntries,'foundation_conflict_fields':foundationConflictFields,'foundation_conditional_provenance':foundationConditionalProvenance,'s5_feature_payload':s5FeaturePayload,'execution_engine':executionEngine,'execution_tier':executionTier,'fallback_used':fallbackUsed,'door_address':doorAddress,'lineage_snapshot':lineageSnapshot,'coordination_id':coordinationId,'coordination_members':coordinationMembers,'delivery_id':deliveryId,'delivery_recipient':deliveryRecipient,'delivery_status':deliveryStatus,'observations':observations,'findings':findings,'evidence':evidence,'activity':activity,'error':error};
}
