import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

class S7EnvironmentPage extends StatefulWidget { const S7EnvironmentPage({super.key}); @override State<S7EnvironmentPage> createState()=>_S7EnvironmentPageState(); }
class _S7EnvironmentPageState extends State<S7EnvironmentPage> with SingleTickerProviderStateMixin {
 String room='collaboration'; Map<String,dynamic>? session, selected; bool busy=false; String? error; late final AnimationController motion=AnimationController(vsync:this,duration:const Duration(seconds:14))..repeat();
 final task=TextEditingController(text:'Compare two possible explanations for the supplied observation.'); final contextText=TextEditingController(text:'Local synthetic research context supplied by the human.');
 @override void dispose(){motion.dispose();task.dispose();contextText.dispose();super.dispose();}
 Future<void> run() async {setState((){busy=true;error=null;selected=null;});try{final r=await http.post(Uri.parse('http://127.0.0.1:8017/api/s7/sessions'),headers:{'content-type':'application/json'},body:jsonEncode({'task':task.text,'context':{'description':contextText.text}}));final b=jsonDecode(r.body);if(r.statusCode>=400)throw Exception(b['error']);setState(()=>session=b);}catch(e){setState(()=>error='$e');}finally{if(mounted)setState(()=>busy=false);}}
 Future<void> intervene(String action,{String instruction=''}) async {if(session==null||selected==null)return;setState(()=>busy=true);try{final r=await http.post(Uri.parse('http://127.0.0.1:8017/api/s7/sessions/${session!['session_id']}/intervene'),headers:{'content-type':'application/json'},body:jsonEncode({'artifact_id':selected!['artifact_id'],'action':action,'instruction':instruction}));final b=jsonDecode(r.body);if(r.statusCode>=400)throw Exception(b['error']);setState(()=>session=b);}catch(e){setState(()=>error='$e');}finally{if(mounted)setState(()=>busy=false);}}
 Future<void> challenge() async {if(selected==null)return;final c=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(ctx)=>AlertDialog(title:const Text('Challenge analytical object'),content:TextField(controller:c,maxLines:5,decoration:const InputDecoration(hintText:'State the objection or alternative context.')),actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('CANCEL')),FilledButton(onPressed:()=>Navigator.pop(ctx,c.text.trim().isNotEmpty),child:const Text('CREATE BRANCH'))]));if(ok==true)await intervene('challenge',instruction:c.text.trim());c.dispose();}
 @override Widget build(BuildContext c){final a=(session?['artifacts'] as List?)?.whereType<Map<String,dynamic>>().toList()??[];return Scaffold(backgroundColor:const Color(0xff04060d),body:AnimatedBuilder(animation:motion,builder:(_,__)=>Stack(children:[CustomPaint(size:Size.infinite,painter:_Backdrop(motion.value,room)),SafeArea(child:Row(children:[_rail(),Expanded(child:_body(a))])),if(busy)const Positioned(top:0,left:0,right:0,child:LinearProgressIndicator()),if(error!=null)Positioned(bottom:12,left:230,right:30,child:_error())])));}
 Widget _error()=>Material(color:Colors.red.withValues(alpha:.15),borderRadius:BorderRadius.circular(12),child:Padding(padding:const EdgeInsets.all(10),child:Row(children:[const Icon(Icons.warning_amber,size:15),const SizedBox(width:8),Expanded(child:Text(error!,style:const TextStyle(fontSize:9))),IconButton(onPressed:()=>setState(()=>error=null),icon:const Icon(Icons.close,size:15))])));
 Widget _rail()=>SizedBox(width:205,child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Text('S7',style:TextStyle(fontSize:26,fontWeight:FontWeight.w900)),const Text('REASONING RESEARCH BUREAU',style:TextStyle(fontSize:9,letterSpacing:1.5,color:Colors.white38)),const SizedBox(height:28),_nav('collaboration',Icons.groups_rounded,'Collaboration Room','shared intelligence'),_nav('vivren',Icons.visibility_rounded,'Critical Intelligence','Vivren'),_nav('tarkis',Icons.account_tree_rounded,'Hypothesis Exploration','Tarkis'),const Spacer(),Text(session==null?'READY':session!['status'].toString().toUpperCase(),style:const TextStyle(fontSize:9,color:Colors.white38))])));
 Widget _nav(String id,IconData icon,String title,String sub)=>Padding(padding:const EdgeInsets.only(bottom:8),child:Material(color:room==id?Colors.white.withValues(alpha:.10):Colors.transparent,borderRadius:BorderRadius.circular(15),child:InkWell(onTap:(){setState((){room=id;selected=null;});},borderRadius:BorderRadius.circular(15),child:Padding(padding:const EdgeInsets.all(13),child:Row(children:[Icon(icon,size:20,color:room==id?const Color(0xffc8b7ff):Colors.white38),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:TextStyle(fontSize:10,fontWeight:FontWeight.w700,color:room==id?Colors.white:Colors.white54)),Text(sub,style:const TextStyle(fontSize:8,color:Colors.white30))]))])))));
 Widget _body(List<Map<String,dynamic>> a){if(room=='vivren')return _chamber('CRITICAL INTELLIGENCE CHAMBER','VIVREN','Inspect assumptions, evidence, objections and epistemic limits.',const Color(0xffc4b2ff),a.where((x)=>['evaluation','limitation','objection'].contains(x['kind'])).toList());if(room=='tarkis')return _chamber('HYPOTHESIS EXPLORATION CHAMBER','TARKIS','Explore alternatives, branches, counterfactuals and refinement.',const Color(0xffffbd78),a.where((x)=>['hypothesis','comparison','reasoning','result'].contains(x['kind'])).toList());return _collaboration(a);}
 Widget _collaboration(List<Map<String,dynamic>> a)=>_frame('COLLABORATION ROOM','VIVREN ↔ SHARED WORK ↔ TARKIS ↕ HUMAN',const Color(0xffc8b7ff),Column(children:[_request(),const SizedBox(height:12),Expanded(child:Row(children:[Expanded(flex:3,child:_panel('REASONING DEPENDENCY MAP',_graph())),const SizedBox(width:12),Expanded(flex:2,child:_panel('CURRENT INTELLIGENCE',ListView(children:[_stat('Artifacts',a.length),_stat('Branches',((session?['branches'] as List?)?.length??0)),_stat('Interventions',((session?['interventions'] as List?)?.length??0)),const Divider(color:Colors.white10),...a.take(10).map(_compact)])))]))]));
 Widget _request()=>Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.white.withValues(alpha:.055),borderRadius:BorderRadius.circular(17),border:Border.all(color:Colors.white10)),child:Row(crossAxisAlignment:CrossAxisAlignment.end,children:[Expanded(child:TextField(controller:task,maxLines:2,decoration:const InputDecoration(labelText:'Task'))),const SizedBox(width:12),Expanded(child:TextField(controller:contextText,maxLines:2,decoration:const InputDecoration(labelText:'Structured context'))),const SizedBox(width:12),FilledButton.icon(onPressed:busy?null:run,icon:const Icon(Icons.play_arrow),label:const Text('RUN'))]));
 Widget _graph(){final n=(session?['reasoning_graph']?['nodes'] as List?)?.whereType<Map<String,dynamic>>().toList()??[];if(n.isEmpty)return const _Empty('Run a request to populate the live reasoning map.');return ListView(children:[for(final x in n)_graphNode(x)]);}
 Widget _graphNode(Map<String,dynamic> n)=>InkWell(onTap:()=>_select(n),child:Container(margin:const EdgeInsets.only(bottom:7),padding:const EdgeInsets.all(11),decoration:BoxDecoration(color:Colors.white.withValues(alpha:.035),borderRadius:BorderRadius.circular(11),border:Border.all(color:Colors.white10)),child:Row(children:[const Icon(Icons.radio_button_unchecked,size:14,color:Colors.white38),const SizedBox(width:10),Expanded(child:Text(n['label']?.toString()??n['title']?.toString()??'Reasoning node',style:const TextStyle(fontSize:10,fontWeight:FontWeight.w700))),Text(n['stage']?.toString()??'',style:const TextStyle(fontSize:8,color:Colors.white30))])));
 Widget _chamber(String title,String character,String sub,Color accent,List<Map<String,dynamic>> a)=>_frame(title,'$character · $sub',accent,Row(children:[Expanded(flex:2,child:_panel('CANONICAL PARTICIPANT',Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[_orb(character,accent),const SizedBox(height:12),Text(character,style:const TextStyle(fontWeight:FontWeight.w900,letterSpacing:2)),Text(_characterState(character),style:TextStyle(fontSize:8,color:accent))]))),const SizedBox(width:12),Expanded(flex:5,child:_panel(character=='VIVREN'?'CRITICAL FINDINGS':'HYPOTHESIS FIELD',a.isEmpty?const _Empty('No matching analytical objects yet.'):ListView(children:[for(final x in a)_object(x,accent)]))),if(selected!=null)const SizedBox(width:12),if(selected!=null)Expanded(flex:3,child:_panel('DEEP INSPECTION',_inspection()))]));
 String _characterState(String c)=>((session?['character_states'] as Map?)?[c.toLowerCase()] as Map?)?['state']?.toString()??'idle';
 Widget _orb(String who,Color accent)=>Container(width:130,height:130,decoration:BoxDecoration(shape:BoxShape.circle,gradient:RadialGradient(colors:[accent.withValues(alpha:.32),Colors.transparent]),boxShadow:[BoxShadow(color:accent.withValues(alpha:.16),blurRadius:36)]),child:Icon(who=='VIVREN'?Icons.visibility_rounded:Icons.account_tree_rounded,size:43,color:accent));
 Widget _object(Map<String,dynamic> x,Color accent)=>InkWell(onTap:()=>_select(x),child:Container(margin:const EdgeInsets.only(bottom:8),padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Colors.white.withValues(alpha:.035),borderRadius:BorderRadius.circular(12)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(x['title']?.toString()??'Analytical object',style:const TextStyle(fontSize:10,fontWeight:FontWeight.w700))),Text('v${x['version']??1}',style:TextStyle(fontSize:8,color:accent))]),Text('${x['kind']} · branch ${x['branch_id']}',style:const TextStyle(fontSize:8,color:Colors.white30)),const SizedBox(height:5),Text(_json(x['content']),maxLines:3,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:9,color:Colors.white54))]));
 Widget _inspection(){final l=(session?['lineage'] as Map?)?[selected!['artifact_id']];final p=(session?['provenance'] as Map?)?[selected!['artifact_id']];return ListView(children:[Text(selected!['title']?.toString()??'Artifact',style:const TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:8),_kv('Kind',selected!['kind']),_kv('Version','${selected!['version']}'),_kv('Branch',selected!['branch_id']),_kv('Parents',((selected!['parent_ids'] as List?)??[]).join(', ')),_kv('Children',((l as Map?)?['children'] as List? ?? []).join(', ')),const Divider(color:Colors.white10),const Text('PROVENANCE',style:TextStyle(fontSize:8,color:Colors.white38)),Text(_json(p),style:const TextStyle(fontSize:8,color:Colors.white60)),const SizedBox(height:10),const Text('CONTENT',style:TextStyle(fontSize:8,color:Colors.white38)),Text(_json(selected!['content']),style:const TextStyle(fontSize:9,color:Colors.white60)),const SizedBox(height:12),_interventionBar()]);}
 Widget _interventionBar()=>Wrap(spacing:6,runSpacing:6,children:[OutlinedButton(onPressed:busy?null:challenge,child:const Text('CHALLENGE',style:TextStyle(fontSize:8))),OutlinedButton(onPressed:busy?null:()=>intervene('request_context',instruction:'Supply additional structured context.'),child:const Text('REQUEST CONTEXT',style:TextStyle(fontSize:8))),OutlinedButton(onPressed:busy?null:()=>intervene('reject',instruction:'Human rejected this object.'),child:const Text('REJECT',style:TextStyle(fontSize:8))),OutlinedButton(onPressed:busy?null:()=>intervene('continue'),child:const Text('CONTINUE',style:TextStyle(fontSize:8)))]);
 Widget _compact(Map<String,dynamic> x)=>ListTile(dense:true,onTap:()=>_select(x),title:Text(x['title']?.toString()??'Artifact',style:const TextStyle(fontSize:9)),subtitle:Text('${x['kind']} · ${x['branch_id']}',style:const TextStyle(fontSize:8,color:Colors.white30)));
 Widget _stat(String l,int v)=>ListTile(dense:true,leading:const Icon(Icons.data_object,size:15,color:Colors.white30),title:Text(l,style:const TextStyle(fontSize:9,color:Colors.white45)),trailing:Text('$v',style:const TextStyle(fontWeight:FontWeight.w800)));
 Widget _kv(String k,String v)=>Padding(padding:const EdgeInsets.symmetric(vertical:3),child:Row(children:[SizedBox(width:65,child:Text(k,style:const TextStyle(fontSize:8,color:Colors.white30))),Expanded(child:Text(v,style:const TextStyle(fontSize:8,color:Colors.white60)))]));
 String _json(dynamic v)=>v is Map?const JsonEncoder.withIndent('  ').convert(v):v?.toString()??'No content';
 void _select(Map<String,dynamic> n){final id=n['artifact_id'];final all=(session?['artifacts'] as List?)?.whereType<Map<String,dynamic>>().toList()??[];setState(()=>selected=all.cast<Map<String,dynamic>?>().firstWhere((x)=>x?['artifact_id']==id,orElse:()=>n));}
 Widget _frame(String title,String sub,Color accent,Widget child)=>Padding(padding:const EdgeInsets.fromLTRB(6,8,24,20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Container(width:4,height:38,decoration:BoxDecoration(color:accent,borderRadius:BorderRadius.circular(3))),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900)),Text(sub,style:const TextStyle(fontSize:9,color:Colors.white38))]))]),const SizedBox(height:12),Expanded(child:child)]));
 Widget _panel(String title,Widget child)=>Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.white.withValues(alpha:.055),borderRadius:BorderRadius.circular(17),border:Border.all(color:Colors.white.withValues(alpha:.09))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontSize:8,letterSpacing:1.4,color:Colors.white38,fontWeight:FontWeight.w800)),const SizedBox(height:9),Flexible(child:child)]));
}
class _Empty extends StatelessWidget{final String text;const _Empty(this.text);@override Widget build(BuildContext c)=>Center(child:Text(text,textAlign:TextAlign.center,style:const TextStyle(color:Colors.white30,fontSize:10)));}
class _Backdrop extends CustomPainter{final double t;final String room;_Backdrop(this.t,this.room);@override void paint(Canvas c,Size s){final base=room=='vivren'?const Color(0xff17102b):room=='tarkis'?const Color(0xff24170d):const Color(0xff10172b);c.drawRect(Offset.zero&s,Paint()..shader=RadialGradient(radius:1.2,colors:[base,const Color(0xff04060d)]).createShader(Offset.zero&s));final p=Paint()..color=Colors.white.withValues(alpha:.06);for(var i=0;i<40;i++)c.drawCircle(Offset((i*91+t*20)%s.width,(i*47+t*8)%s.height),1,p);}@override bool shouldRepaint(covariant _Backdrop o)=>o.t!=t||o.room!=room;}
