import 'package:flutter/material.dart';
import 'presentation/runtime_client.dart';
import 'presentation/presentation_state.dart';
import 'interaction/bloom.dart';
import 'bloom_page.dart';
import 'analysis_page.dart';
import 'chat/character_chat_page.dart';

class CriterivoxShell extends StatefulWidget{const CriterivoxShell({super.key});@override State<CriterivoxShell> createState()=>_ShellState();}
class _ShellState extends State<CriterivoxShell>{final runtime=CharacterRuntimeClient();final task=TextEditingController(text:'Analyze the supplied information in its current context.');final data=TextEditingController(text:'Local sample dataset');final ctx=TextEditingController(text:'Synthetic local research context');PresentationState? state;String page='bloom';bool busy=false;
@override void initState(){super.initState();runtime.states.listen((v){if(mounted)setState((){state=v;busy=false;});});runtime.errors.listen((_){if(mounted)setState(()=>busy=false);});runtime.connect();}
@override void dispose(){runtime.dispose();task.dispose();data.dispose();ctx.dispose();super.dispose();}
void open(String p)=>setState(()=>page=p);void send(String m){setState(()=>busy=true);runtime.sendChat(message:m,data:{'dataset':data.text,'records':3},context:{'description':ctx.text,'origin':'Syvax'});}void start(){setState(()=>busy=true);runtime.requestApplication(intent:'analyze',task:task.text,data:{'dataset':data.text,'records':3},context:{'description':ctx.text,'origin':'Analysis Workspace'},source:'workspace');}
@override Widget build(BuildContext c)=>Scaffold(body:Row(children:[_Rail(page:page,onOpen:open),Expanded(child:Column(children:[const _Top(),Expanded(child:page=='chat'?CharacterChatPage(state:state,busy:busy,onSend:send,onOpenTask:()=>open('workspace')):page=='workspace'?AnalysisPage(state:state,busy:busy,task:task,data:data,contextText:ctx,onStart:start,onChat:()=>open('chat')):BloomPage(onSub:(v)=>open(v==BloomSuboption.workspace?'workspace':'chat'),onSyvax:send,busy:busy)]))])));}
}
class _Rail extends StatelessWidget{final String page;final ValueChanged<String> onOpen;const _Rail({required this.page,required this.onOpen});@override Widget build(BuildContext c)=>Container(width:220,padding:const EdgeInsets.all(12),decoration:const BoxDecoration(color:Color(0xCC050712),border:Border(right:BorderSide(color:Color(0x202A2F4B)))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Padding(padding:EdgeInsets.all(12),child:Text('CRITERIVOX',style:TextStyle(color:Colors.white,fontSize:20,fontWeight:FontWeight.w800))),const SizedBox(height:20),_N('BLOOM',Icons.auto_awesome_rounded,page=='bloom',()=>onOpen('bloom')),const SizedBox(height:14),const Text('CAPABILITIES',style:TextStyle(color:Color(0xFF69718E),fontSize:9,fontWeight:FontWeight.w700)),_N('Analyze',Icons.bar_chart_rounded,page=='workspace',()=>onOpen('workspace')),_N('Compare',Icons.balance_rounded,false,()=>{}),_N('Explore',Icons.search_rounded,false,()=>{}),_N('Plan',Icons.calendar_month_rounded,false,()=>{}),_N('Insights',Icons.lightbulb_outline_rounded,false,()=>{}),_N('Explain',Icons.chat_bubble_outline_rounded,false,()=>{}),const SizedBox(height:14),const Text('QUICK ACTIONS',style:TextStyle(color:Color(0xFF69718E),fontSize:9,fontWeight:FontWeight.w700)),_N('Analysis Workspace',Icons.dashboard_customize_rounded,page=='workspace',()=>onOpen('workspace')),_N('Character Chat',Icons.forum_rounded,page=='chat',()=>onOpen('chat')),const Spacer(),const Text('Syvax coordinates dialogue and character handoff.',style:TextStyle(color:Color(0xFF69718D),fontSize:10))]);}
Widget _n(String t,IconData i,bool a,VoidCallback tap)=>ListTile(onTap:tap,selected:a,selectedTileColor:const Color(0x55362A86),dense:true,leading:Icon(i,size:17,color:a?const Color(0xFFB8A8FF):const Color(0xFF7B839D)),title:Text(t,style:TextStyle(color:a?Colors.white:const Color(0xFF9AA1B7),fontSize:11,fontWeight:a?FontWeight.w700:FontWeight.w500)));}
class _Top extends StatelessWidget{const _Top();@override Widget build(BuildContext c)=>Container(height:70,padding:const EdgeInsets.symmetric(horizontal:24),decoration:const BoxDecoration(border:Border(bottom:BorderSide(color:Color(0x202A2F4B)))),child:const Row(children:[Text('Research Intelligence Workspace',style:TextStyle(color:Color(0xFFD8DAE6),fontSize:13,fontWeight:FontWeight.w600)),Spacer(),Icon(Icons.notifications_none_rounded),SizedBox(width:20),CircleAvatar(radius:17,backgroundColor:Color(0xFF282340),child:Icon(Icons.person_outline_rounded,size:18))]));}
