import 'package:flutter/material.dart';
import 'interaction/bloom.dart';
import 'interaction/syvax.dart';
import 'presentation/presentation_state.dart';
import 'presentation/criterivox_theme.dart';

class BloomPage extends StatefulWidget {
  final PresentationState? state;
  final ValueChanged<BloomSuboption> onSub;
  final ValueChanged<String> onSyvax;
  final ValueChanged<BloomCapability>? onCapability;
  final VoidCallback onStewardship;
  final VoidCallback onHandoff;
  final bool busy;
  const BloomPage({super.key,required this.state,required this.onSub,required this.onSyvax,this.onCapability,required this.onStewardship,required this.onHandoff,required this.busy});
  @override State<BloomPage> createState()=>_BloomPageState();
}

class _BloomPageState extends State<BloomPage>{
  BloomCapability? selected;
  @override Widget build(BuildContext context){final t=CriterivoxTheme.of(context);return LayoutBuilder(builder:(context,constraints){final compact=constraints.maxWidth<1100;return SingleChildScrollView(padding:EdgeInsets.all(compact?16:22),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[_HeroHeader(state:widget.state,selected:selected),const SizedBox(height:14),if(compact)Column(children:[_BloomCard(state:widget.state,selected:selected,onCapability:_select,onSub:widget.onSub,height:560),const SizedBox(height:14),_SandreQuickActions(state:widget.state,onOpen:widget.onStewardship,onHandoff:widget.onHandoff),const SizedBox(height:14),Syvax(onSubmit:widget.onSyvax,busy:widget.busy),const SizedBox(height:14),_ActivityPanel(state:widget.state)]) else Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:_BloomCard(state:widget.state,selected:selected,onCapability:_select,onSub:widget.onSub,height:600)),const SizedBox(width:16),SizedBox(width:320,child:Column(children:[_SandreQuickActions(state:widget.state,onOpen:widget.onStewardship,onHandoff:widget.onHandoff),const SizedBox(height:14),Syvax(onSubmit:widget.onSyvax,busy:widget.busy),const SizedBox(height:14),_ActivityPanel(state:widget.state)]))]),const SizedBox(height:14),_Lifecycle(state:widget.state),const SizedBox(height:10),Text('Criterivox stays alive through state, motion, handoff, and context. The visual layer reflects the system instead of inventing it.',style:TextStyle(color:t.mutedText,fontSize:10.5,height:1.45))]));});}
  void _select(BloomCapability value){setState(()=>selected=selected==value?null:value);widget.onCapability?.call(value);}
}

class _HeroHeader extends StatelessWidget{final PresentationState? state;final BloomCapability? selected;const _HeroHeader({required this.state,required this.selected});@override Widget build(BuildContext context){final t=CriterivoxTheme.of(context);final selectedText=selected==null?'Choose a capability, then choose how you want to work with it.':'${Bloom.labels[selected!]} selected. Choose the relevant path.';return Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Living Interaction',style:TextStyle(color:t.text,fontSize:23,fontWeight:FontWeight.w700)),const SizedBox(height:4),Text(selectedText,style:TextStyle(color:t.mutedText,fontSize:11.5))])),if(state?.taskId!=null)Container(padding:const EdgeInsets.symmetric(horizontal:12,vertical:8),decoration:BoxDecoration(color:t.surfaceStrong,borderRadius:BorderRadius.circular(12),border:Border.all(color:t.border)),child:Text('TASK ${state!.taskId}',style:TextStyle(color:t.mutedText,fontSize:9,fontWeight:FontWeight.w700))) ]);}}

class _BloomCard extends StatelessWidget{final PresentationState? state;final BloomCapability? selected;final ValueChanged<BloomCapability> onCapability;final ValueChanged<BloomSuboption> onSub;final double height;const _BloomCard({required this.state,required this.selected,required this.onCapability,required this.onSub,required this.height});@override Widget build(BuildContext context){final t=CriterivoxTheme.of(context);return Container(height:height,padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:t.surface.withValues(alpha:.72),borderRadius:BorderRadius.circular(24),border:Border.all(color:t.border)),child:Column(children:[Container(padding:const EdgeInsets.symmetric(horizontal:16,vertical:10),decoration:BoxDecoration(color:t.surfaceStrong,borderRadius:BorderRadius.circular(16),border:Border.all(color:t.border)),child:Row(children:[Icon(Icons.auto_awesome_rounded,color:t.primary,size:18),const SizedBox(width:9),Expanded(child:Text('Choose a capability. Data Stewardship now routes to Sandre and the real foundation workflow.',style:TextStyle(color:t.mutedText,fontSize:10.5))),Icon(Icons.open_in_full_rounded,color:t.mutedText,size:16)])),const SizedBox(height:8),Expanded(child:Center(child:Bloom(onSelected:onCapability,selected:selected,onSuboption:onSub))) ]));}}

class _SandreQuickActions extends StatelessWidget{final PresentationState? state;final VoidCallback onOpen;final VoidCallback onHandoff;const _SandreQuickActions({required this.state,required this.onOpen,required this.onHandoff});@override Widget build(BuildContext context){final t=CriterivoxTheme.of(context);final foundation=state?.foundationId;final confirmed=state?.foundationConfirmation=='user-confirmed'||state?.foundationConfirmation=='user-corrected';return Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:t.surface,borderRadius:BorderRadius.circular(20),border:Border.all(color:t.border)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Icon(Icons.inventory_2_rounded,color:t.primary,size:19),const SizedBox(width:8),Expanded(child:Text('Sandre Quick Actions',style:TextStyle(color:t.text,fontSize:14,fontWeight:FontWeight.w700)))]),const SizedBox(height:6),Text(foundation==null?'No foundation is active.':'Foundation $foundation • ${state?.foundationCandidateCount??0} candidate(s) • ${state?.foundationConfirmation??'uncertain'}',style:TextStyle(color:t.mutedText,fontSize:9.5,height:1.35)),const SizedBox(height:12),_action('Open Data Stewardship',Icons.folder_special_rounded,onOpen,t),_action('Review Foundation',Icons.fact_check_outlined,onOpen,t),_action('Handoff to Dharen',Icons.send_rounded,confirmed?onHandoff:null,t)]));}
  Widget _action(String label,IconData icon,VoidCallback? onTap,CriterivoxTheme t)=>Padding(padding:const EdgeInsets.only(bottom:7),child:SizedBox(width:double.infinity,child:OutlinedButton.icon(onPressed:onTap,icon:Icon(icon,size:15),label:Text(label))));
}

class _ActivityPanel extends StatelessWidget{final PresentationState? state;const _ActivityPanel({required this.state});@override Widget build(BuildContext context){final t=CriterivoxTheme.of(context);final items=<String>[if(state?.message!=null)state!.message!,...?state?.activity.take(3),'Analysis workspace is available from the same task.','Syvax can route a request to Dharen.'];return Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:t.surface,borderRadius:BorderRadius.circular(20),border:Border.all(color:t.border)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text('Recent Activity',style:TextStyle(color:t.text,fontSize:15,fontWeight:FontWeight.w700))),Text(state?.error==null?'LIVE':'WARNING',style:TextStyle(color:state?.error==null?t.success:t.warning,fontSize:9,fontWeight:FontWeight.w800))]),const SizedBox(height:14),for(final item in items.take(6))Padding(padding:const EdgeInsets.only(bottom:12),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(Icons.circle,size:6,color:t.primary),const SizedBox(width:10),Expanded(child:Text(item,style:TextStyle(color:t.mutedText,fontSize:10.5,height:1.4)))]))]));}}

class _Lifecycle extends StatelessWidget{final PresentationState? state;const _Lifecycle({required this.state});@override Widget build(BuildContext context){final t=CriterivoxTheme.of(context);final active=state?.taskState??'READY';final stages=['CREATED','RECEIVED','VALIDATING','PROCESSING','ANALYZING','RESULT_READY','COMPLETED'];final activeIndex=stages.indexOf(active.toUpperCase());return Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:t.surface,borderRadius:BorderRadius.circular(20),border:Border.all(color:t.border)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('TASK LIFECYCLE',style:TextStyle(color:t.mutedText,fontSize:10,fontWeight:FontWeight.w700,letterSpacing:1.1)),const SizedBox(height:18),SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(mainAxisSize:MainAxisSize.min,children:[for(var i=0;i<stages.length;i++)Row(children:[Column(mainAxisSize:MainAxisSize.min,children:[Container(width:30,height:30,decoration:BoxDecoration(shape:BoxShape.circle,color:i<=activeIndex?t.primary.withValues(alpha:.15):t.surfaceStrong,border:Border.all(color:i<=activeIndex?t.primary:t.border)),child:Icon(i==6?Icons.check_rounded:Icons.auto_awesome_rounded,size:14,color:i<=activeIndex?t.primary:t.mutedText)),const SizedBox(height:6),Text(stages[i].replaceAll('_',' '),style:TextStyle(color:i==activeIndex?t.text:t.mutedText,fontSize:8.5,fontWeight:FontWeight.w600))]),if(i<stages.length-1)Container(width:42,height:1,margin:const EdgeInsets.symmetric(horizontal:6,vertical:15),color:t.border)])])),const SizedBox(height:10),Text('Current state: $active',style:TextStyle(color:t.mutedText,fontSize:10))]));}
}