import 'dart:convert';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'interaction/home03_bloom.dart';
import 'interaction/syvax.dart';
import 'presentation/criterivox_theme.dart';

class Home03SyvaxPage extends StatefulWidget { final ValueChanged<String> onOpen; const Home03SyvaxPage({super.key,required this.onOpen}); @override State<Home03SyvaxPage> createState()=>_Home03SyvaxPageState(); }
class _Home03SyvaxPageState extends State<Home03SyvaxPage>{
 final controller=TextEditingController(),correction=TextEditingController(); Map<String,dynamic>? plan,bloom,rendered; String mode='HITL',view='executive'; bool busy=false;
 Uri get base{final scheme=Uri.base.scheme=='https'?'https':'http';final host=Uri.base.host.isEmpty?'127.0.0.1':Uri.base.host;return Uri.parse('$scheme://$host:${const String.fromEnvironment('CRITERIVOX_BACKEND_PORT',defaultValue:'8000')}');}
 Future<Map<String,dynamic>> post(String path,Map<String,dynamic> body)async{final r=await http.post(base.replace(path:'${base.path}$path'),headers:{'content-type':'application/json'},body:jsonEncode(body));final d=Map<String,dynamic>.from(jsonDecode(r.body) as Map);if(r.statusCode>=400)throw Exception('${d['detail']??d['safety']??'Request failed'}');return d;}
 Future<void> loadBloom()async{try{final r=await http.get(base.replace(path:'${base.path}/api/bloom/state'));if(r.statusCode<300&&mounted)setState(()=>bloom=Map<String,dynamic>.from(jsonDecode(r.body) as Map));}catch(_){}}
 Future<void> dispatch(String text)async{if(text.trim().isEmpty||busy)return;setState(()=>busy=true);try{final d=await post('/api/syvax/dispatch',{'message':text.trim(),'data':{'origin':'home03-syvax'},'context':{'entered_through':'Home 03'}});final r=await post('/api/syvax/render',{'text':text.trim(),'intent':d['plan']['intent']['intent_type']});setState(()=>{plan=d;rendered=r});await loadBloom();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}finally{if(mounted)setState(()=>busy=false);}}
 Future<void> attach()async{final result=await FilePicker.platform.pickFiles(withData:true,allowMultiple:false);if(result==null||result.files.isEmpty)return;final f=result.files.single;final bytes=f.bytes;if(bytes==null||bytes.length>8*1024*1024){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Universal Dropzone accepts files up to 8 MB.')));return;}try{final r=await post('/api/home03/ingest',{'filename':f.name,'content_type':f.extension,'content_base64':base64Encode(bytes)});if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Sent to Sandre · foundation ${r['foundation_id']}')));await loadBloom();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}}
 @override void initState(){super.initState();loadBloom();}
 @override void dispose(){controller.dispose();correction.dispose();super.dispose();}
 @override Widget build(BuildContext context){final t=CriterivoxTheme.of(context);final p=plan?['plan'];final steps=p is Map&&p['steps'] is List?List<Map<String,dynamic>>.from((p['steps'] as List).map((e)=>Map<String,dynamic>.from(e))):<Map<String,dynamic>>[];return Scaffold(backgroundColor:t.page,body:SafeArea(child:CustomScrollView(slivers:[SliverPadding(padding:const EdgeInsets.fromLTRB(20,18,20,30),sliver:SliverList(delegate:SliverChildListDelegate([
 Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('HOME 03 · SYVAX',style:TextStyle(color:t.primary,fontSize:10,fontWeight:FontWeight.w800,letterSpacing:1.4)),const SizedBox(height:4),Text('Interaction & Gateway',style:TextStyle(color:t.text,fontSize:28,fontWeight:FontWeight.w700)),Text('Dialogue · routing · safety · steering · output translation',style:TextStyle(color:t.mutedText,fontSize:11))])),_mode(t)]),const SizedBox(height:16),
 LayoutBuilder(builder:(c,k)=>k.maxWidth<1000?Column(children:[_radar(t,steps),const SizedBox(height:14),Syvax(onSubmit:dispatch,busy:busy),const SizedBox(height:14),_bloom(t)]):Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(flex:6,child:_radar(t,steps)),const SizedBox(width:14),Expanded(flex:3,child:Column(children:[Syvax(onSubmit:dispatch,busy:busy),const SizedBox(height:14),_bloom(t)]))])),const SizedBox(height:14),_dropzone(t),const SizedBox(height:14),_workbench(t,p),const SizedBox(height:14),_steering(t)]))) ]))));}
 Widget _mode(CriterivoxTheme t)=>Container(padding:const EdgeInsets.all(4),decoration:BoxDecoration(color:t.surfaceStrong,borderRadius:BorderRadius.circular(14),border:Border.all(color:t.border)),child:Row(children:[for(final m in ['HITL','HOTL'])TextButton(onPressed:busy?null:()async{await post('/api/syvax/oversight',{'mode':m});await post('/api/bloom/mode',{'mode':m});setState(()=>mode=m);await loadBloom();},style:TextButton.styleFrom(backgroundColor:mode==m?t.primary.withValues(alpha:.18):Colors.transparent),child:Text(m,style:TextStyle(color:mode==m?t.text:t.mutedText,fontSize:10,fontWeight:FontWeight.w700))) ]));
 Widget _radar(CriterivoxTheme t,List<Map<String,dynamic>> steps)=>Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:t.surface,borderRadius:BorderRadius.circular(22),border:Border.all(color:t.border)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text('TASK ROUTING RADAR',style:TextStyle(color:t.text,fontWeight:FontWeight.w800,fontSize:11,letterSpacing:1))),Text(plan==null?'READY':'${steps.length} STAGES',style:TextStyle(color:t.primary,fontSize:9,fontWeight:FontWeight.w800))]),const SizedBox(height:16),Wrap(spacing:8,runSpacing:8,children:[_routeNode(t,'SYVAX','reception'),for(final s in steps)_routeNode(t,'${s['actor']}','${s['home']} · ${s['capability']}')]),const SizedBox(height:14),Text(plan==null?'Send a task through Syvax to compile and dispatch an adaptive execution plan.':'${pText(plan)}',style:TextStyle(color:t.mutedText,fontSize:10.5,height:1.4))]));
 String pText(Map<String,dynamic>? d){final p=d?['plan'];if(p is! Map)return '';final i=p['intent'];return '${i is Map?i['intent_type']:'task'} · confidence ${(((i is Map?(i['confidence']??0):0) as num).toDouble()*100).round()}% · ${p['task_id']}';}
 Widget _routeNode(CriterivoxTheme t,String title,String sub)=>Container(width:145,padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:t.surfaceStrong,borderRadius:BorderRadius.circular(14),border:Border.all(color:title=='SYVAX'?t.primary:t.border)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:TextStyle(color:t.text,fontSize:11,fontWeight:FontWeight.w800)),const SizedBox(height:3),Text(sub,style:TextStyle(color:t.mutedText,fontSize:8.5))]));
 Widget _dropzone(CriterivoxTheme t)=>InkWell(onTap:attach,borderRadius:BorderRadius.circular(22),child:Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:t.surface,borderRadius:BorderRadius.circular(22),border:Border.all(color:t.primary.withValues(alpha:.55))),child:Row(children:[Icon(Icons.upload_file_rounded,color:t.primary),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('UNIVERSAL DROPZONE',style:TextStyle(color:t.text,fontWeight:FontWeight.w800,fontSize:11)),Text('Voice/image/document/code payload → normalize → Sandre / Data Foundation',style:TextStyle(color:t.mutedText,fontSize:9))])),Text('ATTACH',style:TextStyle(color:t.primary,fontSize:9,fontWeight:FontWeight.w800))]));
 Widget _workbench(CriterivoxTheme t,dynamic p)=>Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:t.surface,borderRadius:BorderRadius.circular(22),border:Border.all(color:t.border)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text('SYVAX LENS · UI WORKBENCH',style:TextStyle(color:t.text,fontSize:11,fontWeight:FontWeight.w800))),for(final v in ['executive','reasoning','json'])Padding(padding:const EdgeInsets.only(left:4),child:TextButton(onPressed:()=>setState(()=>view=v),style:TextButton.styleFrom(backgroundColor:view==v?t.primary.withValues(alpha:.16):Colors.transparent),child:Text(v.toUpperCase(),style:TextStyle(color:view==v?t.primary:t.mutedText,fontSize:8))))]),const SizedBox(height:10),SelectableText(view=='json'?const JsonEncoder.withIndent('  ').convert({'plan':plan,'rendered':rendered,'bloom':bloom}):view=='reasoning'?((p is Map&&p['steps'] is List)?(p['steps'] as List).asMap().entries.map((e)=>'${e.key+1}. ${e.value['actor']} · ${e.value['reason']}').join('\n'):'No execution path yet.'):rendered?['components']?.toString()??'No rendered output yet.':p==null?'No execution result yet.':'Syvax routed the request through ${(p['steps'] as List).map((e)=>e['actor']).join(' → ')}.',style:TextStyle(color:t.mutedText,fontSize:10.5,height:1.6))]));
 Widget _steering(CriterivoxTheme t)=>Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:t.surface,borderRadius:BorderRadius.circular(22),border:Border.all(color:t.border)),child:Row(children:[Expanded(child:TextField(controller:correction,decoration:const InputDecoration(hintText:'Add a mid-flight correction or constraint…'))),const SizedBox(width:10),FilledButton(onPressed:plan==null?null:()=>post('/api/syvax/steer',{'task_id':plan!['plan']['task_id'],'correction':correction.text}).then((_){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Workflow paused. Correction recorded.')));}),child:const Text('Pause & steer'))]));
 Widget _bloom(CriterivoxTheme t)=>Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:t.surface,borderRadius:BorderRadius.circular(22),border:Border.all(color:t.border)),child:Column(children:[Row(children:[Expanded(child:Text('🌸 THE BLOOM · 8 HOMES',style:TextStyle(color:t.text,fontSize:12,fontWeight:FontWeight.w800))),Text('${bloom?['active_homes']?.length??0} ACTIVE',style:TextStyle(color:t.primary,fontSize:9,fontWeight:FontWeight.w800))]),const SizedBox(height:8),Home03Bloom(onOpen:widget.onOpen,state:bloom),const SizedBox(height:8),Row(children:[Expanded(child:Text('Mode: ${bloom?['mode']??mode} · traces ${bloom?['traces']?.length??0} · checkpoints ${bloom?['checkpoints']?.length??0}',style:TextStyle(color:t.mutedText,fontSize:9))),IconButton(onPressed:()=>widget.onOpen('stewardship'),icon:const Icon(Icons.inventory_2_rounded),tooltip:'Open Data Stewardship')]) ]));
}
