import 'package:flutter/material.dart';
import 'character/session_character_animation.dart';
import 'presentation/criterivox_theme.dart';

class WorldPortalPage extends StatelessWidget {
  final VoidCallback onCivilization;
  final VoidCallback onHumanResidence;
  final VoidCallback onGuest;
  final VoidCallback onChat;
  const WorldPortalPage({super.key, required this.onCivilization, required this.onHumanResidence, required this.onGuest, required this.onChat});

  @override
  Widget build(BuildContext context) {
    final t = CriterivoxTheme.of(context);
    return LayoutBuilder(builder: (context, c) {
      final compact = c.maxWidth < 900;
      return SingleChildScrollView(padding: EdgeInsets.all(compact ? 18 : 30), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [
        Container(padding: EdgeInsets.all(compact ? 22 : 36), decoration: BoxDecoration(borderRadius: BorderRadius.circular(30), gradient: LinearGradient(colors: [t.surfaceStrong, t.surface]), border: Border.all(color: t.border)), child: Column(children: [
          Text('WELCOME TO CRITERIVOX', style: TextStyle(color: t.primary, fontSize: 11, fontWeight: FontWeight.w800, letterSpacing: 2.2)),
          const SizedBox(height: 12),
          Text('Two gates. One living system.', textAlign: TextAlign.center, style: TextStyle(color: t.text, fontSize: compact ? 27 : 38, fontWeight: FontWeight.w800)),
          const SizedBox(height: 10),
          Text('First understand the machine. Then bring your own problem into it.', textAlign: TextAlign.center, style: TextStyle(color: t.mutedText, fontSize: 13, height: 1.5)),
        ])),
        const SizedBox(height: 22),
        if (compact) Column(children: [_gate1(t), const SizedBox(height: 14), _gate2(t)]) else Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: _gate1(t)), const SizedBox(width: 16), Expanded(child: _gate2(t))]),
        const SizedBox(height: 18),
        Container(padding: const EdgeInsets.all(18), decoration: BoxDecoration(color: t.surface, borderRadius: BorderRadius.circular(20), border: Border.all(color: t.border)), child: Row(children: [Icon(Icons.forum_rounded, color: t.primary), const SizedBox(width: 12), Expanded(child: Text('Independent character chat is always nearby. Meet a civilian without leaving the world you are exploring.', style: TextStyle(color: t.mutedText, fontSize: 11, height: 1.45))), TextButton(onPressed: onChat, child: const Text('Open chat'))])),
      ]);
    });
  }

  Widget _gate1(CriterivoxTheme t) => _GateCard(t, icon: Icons.door_front_door_rounded, eyebrow: 'GATE 1', title: 'CRITERIVOX CIVILIZATION', subtitle: 'Meet the people who assist you make the decision.', body: 'Explore the internal society: characters, homes, relationships, collaboration, evidence, information movement, reasoning challenges and explanations.', accent: t.primary, onTap: onCivilization, action: 'Enter civilization', child: Wrap(spacing: 8, runSpacing: 8, children: [_chip(t, 'Meet characters'), _chip(t, 'Visit homes'), _chip(t, 'Inspect evidence'), _chip(t, 'Challenge reasoning')],));

  Widget _gate2(CriterivoxTheme t) => _GateCard(t, icon: Icons.home_work_rounded, eyebrow: 'GATE 2', title: 'HUMAN RESIDENCE', subtitle: 'This is where your actual problem lives.', body: 'Create a personal residence, work privately, invite collaborators, or enter with a Guest Pass when you only want to experience decision support.', accent: t.success, onTap: onHumanResidence, action: 'Enter residence', child: Row(children: [Expanded(child: _choice(t, Icons.person_rounded, 'Private house', 'Your personal workspace')), const SizedBox(width: 8), Expanded(child: _choice(t, Icons.groups_rounded, 'Club / building', 'Collaboration space')), const SizedBox(width: 8), Expanded(child: _choice(t, Icons.confirmation_number_rounded, 'Guest Pass', 'Temporary visit', onTap: onGuest))]));

  Widget _GateCard(CriterivoxTheme t, {required IconData icon, required String eyebrow, required String title, required String subtitle, required String body, required Color accent, required VoidCallback onTap, required String action, required Widget child}) => Container(padding: const EdgeInsets.all(22), decoration: BoxDecoration(color: t.surface, borderRadius: BorderRadius.circular(24), border: Border.all(color: accent.withValues(alpha: .3))), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Icon(icon, color: accent, size: 28), const SizedBox(height: 14), Text(eyebrow, style: TextStyle(color: accent, fontSize: 9, fontWeight: FontWeight.w800, letterSpacing: 1.5)), const SizedBox(height: 6), Text(title, style: TextStyle(color: t.text, fontSize: 20, fontWeight: FontWeight.w800)), const SizedBox(height: 5), Text(subtitle, style: TextStyle(color: t.text, fontSize: 11, fontWeight: FontWeight.w600)), const SizedBox(height: 12), Text(body, style: TextStyle(color: t.mutedText, fontSize: 11, height: 1.5)), const SizedBox(height: 16), child, const SizedBox(height: 18), FilledButton.icon(onPressed: onTap, icon: const Icon(Icons.arrow_forward_rounded, size: 16), label: Text(action))]));

  Widget _chip(CriterivoxTheme t, String text) => Container(padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 7), decoration: BoxDecoration(color: t.surfaceStrong, borderRadius: BorderRadius.circular(20), border: Border.all(color: t.border)), child: Text(text, style: TextStyle(color: t.mutedText, fontSize: 9, fontWeight: FontWeight.w600)));
  Widget _choice(CriterivoxTheme t, IconData icon, String title, String sub, {VoidCallback? onTap}) => InkWell(onTap: onTap, borderRadius: BorderRadius.circular(14), child: Container(padding: const EdgeInsets.all(10), decoration: BoxDecoration(color: t.surfaceStrong, borderRadius: BorderRadius.circular(14), border: Border.all(color: t.border)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Icon(icon, size: 17, color: t.primary), const SizedBox(height: 7), Text(title, style: TextStyle(color: t.text, fontSize: 9, fontWeight: FontWeight.w700)), const SizedBox(height: 3), Text(sub, style: TextStyle(color: t.mutedText, fontSize: 8, height: 1.3))])));
}

class CivilizationPage extends StatelessWidget {
  final VoidCallback onBloom;
  final VoidCallback onChat;
  const CivilizationPage({super.key, required this.onBloom, required this.onChat});
  @override Widget build(BuildContext context) { final t=CriterivoxTheme.of(context); final homes=[('Sandre + Kaelen','Data Foundation / Data Stewardship','inventory_2_rounded'),('Dharen + Anuka','Context','hub_rounded'),('Vivren + Tarkis','Intelligence / Reasoning','psychology_rounded'),('Medrus + Epistre + Veridat','Evidence / Experimentation / Verification','science_rounded'),('Pramon + Bodhex','Planning / Decision','account_tree_rounded'),('Manis','Human Challenge','record_voice_over_rounded'),('Viveda','Knowledge','menu_book_rounded'),('Anukor','Cross-home network roamer','device_hub_rounded')]; return SingleChildScrollView(padding: const EdgeInsets.all(26), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('GATE 1',style:TextStyle(color:t.primary,fontSize:10,fontWeight:FontWeight.w800,letterSpacing:2)),const SizedBox(height:7),Text('Criterivox Civilization',style:TextStyle(color:t.text,fontSize:28,fontWeight:FontWeight.w800)),const SizedBox(height:7),Text('Come inside. See how the machine arrived here.',style:TextStyle(color:t.mutedText,fontSize:13)),const SizedBox(height:22),Wrap(spacing:12,runSpacing:12,children:[for(final h in homes)_home(t,h.$1,h.$2,h.$3)]),const SizedBox(height:22),Row(children:[FilledButton.icon(onPressed:onBloom,icon:const Icon(Icons.spa_rounded),label:const Text('Enter Bloom')),const SizedBox(width:10),OutlinedButton.icon(onPressed:onChat,icon:const Icon(Icons.forum_rounded),label:const Text('Independent chat'))]) ])); }
  Widget _home(CriterivoxTheme t,String title,String sub,String iconName){ final icons={'inventory_2_rounded':Icons.inventory_2_rounded,'hub_rounded':Icons.hub_rounded,'psychology_rounded':Icons.psychology_rounded,'science_rounded':Icons.science_rounded,'account_tree_rounded':Icons.account_tree_rounded,'record_voice_over_rounded':Icons.record_voice_over_rounded,'menu_book_rounded':Icons.menu_book_rounded,'device_hub_rounded':Icons.device_hub_rounded}; return Container(width:300,padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:t.surface,borderRadius:BorderRadius.circular(20),border:Border.all(color:t.border)),child:Row(children:[Icon(icons[iconName],color:t.primary),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:TextStyle(color:t.text,fontWeight:FontWeight.w700,fontSize:11)),const SizedBox(height:4),Text(sub,style:TextStyle(color:t.mutedText,fontSize:9,height:1.35))]))])); }
}

class HumanResidencePage extends StatefulWidget { final VoidCallback onGuest; final VoidCallback onWorkspace; const HumanResidencePage({super.key,required this.onGuest,required this.onWorkspace}); @override State<HumanResidencePage> createState()=>_HumanResidencePageState(); }
class _HumanResidencePageState extends State<HumanResidencePage>{bool signedIn=false; @override Widget build(BuildContext context){final t=CriterivoxTheme.of(context);return SingleChildScrollView(padding:const EdgeInsets.all(26),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text('GATE 2',style:TextStyle(color:t.success,fontSize:10,fontWeight:FontWeight.w800,letterSpacing:2)),const SizedBox(height:7),Text('Human Residence',style:TextStyle(color:t.text,fontSize:28,fontWeight:FontWeight.w800)),const SizedBox(height:7),Text('Your house belongs to you. It is not one of the AI characters’ homes.',style:TextStyle(color:t.mutedText,fontSize:13)),const SizedBox(height:22),Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(color:t.surface,borderRadius:BorderRadius.circular(24),border:Border.all(color:t.border)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(signedIn?'YOUR RESIDENCE':'CHOOSE HOW TO ENTER',style:TextStyle(color:t.text,fontSize:15,fontWeight:FontWeight.w800)),const SizedBox(height:12),Text(signedIn?'Your private room and collaboration room are ready.':'Log in / sign up to create your residence, or use Guest Pass for a temporary visit.',style:TextStyle(color:t.mutedText,fontSize:11,height:1.5)),const SizedBox(height:18),Wrap(spacing:10,runSpacing:10,children:[FilledButton.icon(onPressed:(){setState(()=>signedIn=true);widget.onWorkspace();},icon:const Icon(Icons.home_rounded),label:Text(signedIn?'Open private room':'Log in / Sign up')),OutlinedButton.icon(onPressed:widget.onGuest,icon:const Icon(Icons.confirmation_number_rounded),label:const Text('Guest Pass'))]),]),),const SizedBox(height:18),Row(children:[Expanded(child:_room(t,Icons.bed_rounded,'Private Room','Goal → Data + Context → Decisions + Options → Challenge → Act → Result')),const SizedBox(width:12),Expanded(child:_room(t,Icons.groups_rounded,'Collaboration Room','House Owner • Resident • Guest'))]),const SizedBox(height:18),_loop(t)]));}
 Widget _room(CriterivoxTheme t,IconData i,String title,String body)=>Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:t.surface,borderRadius:BorderRadius.circular(20),border:Border.all(color:t.border)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(i,color:t.primary),const SizedBox(height:10),Text(title,style:TextStyle(color:t.text,fontWeight:FontWeight.w700)),const SizedBox(height:7),Text(body,style:TextStyle(color:t.mutedText,fontSize:10,height:1.45))]));
 Widget _loop(CriterivoxTheme t)=>Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:t.surfaceStrong,borderRadius:BorderRadius.circular(20),border:Border.all(color:t.border)),child:Text('HUMAN RESIDENCE\n\nGOAL → DATA + CONTEXT → CRITERIVOX → DECISIONS + OPTIONS → HUMAN CHALLENGE → REJECT / ACCEPT → ACTION → REAL RESULT → RESULTS JOURNAL → FUTURE DECISIONS',style:TextStyle(color:t.text,fontSize:10,height:1.6,fontWeight:FontWeight.w600)));
}

class GuestPassPage extends StatelessWidget { final VoidCallback onWorkspace; const GuestPassPage({super.key,required this.onWorkspace}); @override Widget build(BuildContext context){final t=CriterivoxTheme.of(context);return Center(child:SingleChildScrollView(padding:const EdgeInsets.all(30),child:Container(constraints:const BoxConstraints(maxWidth:680),padding:const EdgeInsets.all(28),decoration:BoxDecoration(color:t.surface,borderRadius:BorderRadius.circular(26),border:Border.all(color:t.primary.withValues(alpha:.3))),child:Column(children:[const Icon(Icons.confirmation_number_rounded,size:42),const SizedBox(height:14),Text('GUEST PASS',style:TextStyle(color:t.primary,fontSize:11,fontWeight:FontWeight.w800,letterSpacing:2)),const SizedBox(height:8),Text('Experience Criterivox before building a house.',textAlign:TextAlign.center,style:TextStyle(color:t.text,fontSize:24,fontWeight:FontWeight.w800)),const SizedBox(height:10),Text('Bring a Goal + Data + Context. Inspect the resulting decision support, then leave without a permanent residence.',textAlign:TextAlign.center,style:TextStyle(color:t.mutedText,fontSize:12,height:1.5)),const SizedBox(height:20),FilledButton.icon(onPressed:onWorkspace,icon:const Icon(Icons.play_arrow_rounded),label:const Text('Start guest workspace'))]))));}}

class BloomSyvaxCompanion extends StatefulWidget { final VoidCallback onBloom; final VoidCallback onChat; final VoidCallback onWorkspace; const BloomSyvaxCompanion({super.key,required this.onBloom,required this.onChat,required this.onWorkspace}); @override State<BloomSyvaxCompanion> createState()=>_BloomSyvaxCompanionState(); }
class _BloomSyvaxCompanionState extends State<BloomSyvaxCompanion>{bool expanded=false; Offset offset=const Offset(0,0); @override Widget build(BuildContext context){final t=CriterivoxTheme.of(context);return Positioned(right:18,bottom:18,child:Material(color:Colors.transparent,child:Column(crossAxisAlignment:CrossAxisAlignment.end,children:[if(expanded)Container(width:300,padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:t.surface.withValues(alpha:.98),borderRadius:BorderRadius.circular(22),border:Border.all(color:t.primary.withValues(alpha:.4)),boxShadow:[BoxShadow(color:Colors.black.withValues(alpha:.28),blurRadius:24)]),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('BLOOM + SYVAX',style:TextStyle(color:t.primary,fontSize:10,fontWeight:FontWeight.w800,letterSpacing:1.4)),const SizedBox(height:5),Text('Your portable system companion',style:TextStyle(color:t.text,fontWeight:FontWeight.w700)),const SizedBox(height:10),Text('Teleport to a civilian, or ask Syvax what is happening and where you can interrupt, steer or challenge the work.',style:TextStyle(color:t.mutedText,fontSize:10,height:1.45)),const SizedBox(height:12),Wrap(spacing:8,runSpacing:8,children:[_action(t,'Bloom',widget.onBloom),_action(t,'Ask Syvax',widget.onChat),_action(t,'Steer work',widget.onWorkspace)])]),const SizedBox(height:8),GestureDetector(onTap:()=>setState(()=>expanded=!expanded),child:Container(width:64,height:64,decoration:BoxDecoration(shape:BoxShape.circle,color:t.surfaceStrong,border:Border.all(color:t.primary,width:1.4),boxShadow:[BoxShadow(color:t.primary.withValues(alpha:.22),blurRadius:18)]),child:Stack(alignment:Alignment.center,children:[for(var i=0;i<8;i++)Transform.rotate(angle:i*3.1415926535/4,child:Container(width:9,height:23,decoration:BoxDecoration(color:t.primary.withValues(alpha:.65),borderRadius:BorderRadius.circular(10)))),const Icon(Icons.record_voice_over_rounded,color:Colors.white,size:20)]))) ])));}
 Widget _action(CriterivoxTheme t,String label,VoidCallback onTap)=>OutlinedButton(onPressed:onTap,child:Text(label,style:const TextStyle(fontSize:9)));
}
