import 'dart:math' as math;
import 'package:flutter/material.dart';
import '../presentation/criterivox_theme.dart';

class Home03Bloom extends StatefulWidget {
 final ValueChanged<String> onOpen; final Map<String,dynamic>? state;
 const Home03Bloom({super.key,required this.onOpen,this.state});
 @override State<Home03Bloom> createState()=>_Home03BloomState();
}
class _Home03BloomState extends State<Home03Bloom> with SingleTickerProviderStateMixin {
 late final AnimationController pulse=AnimationController(vsync:this,duration:const Duration(milliseconds:1100))..repeat(reverse:true);
 static const homes=[['Home 01','Sandre','stewardship'],['Home 02','Dharen','context'],['Home 03','Syvax','home-03'],['Home 04','Vivren / Tarkis','intelligence'],['Home 05','Pramon / Bodhex','planning'],['Home 06','Medrus / Epistre / Veridat','evidence'],['Home 07','Manis','challenge'],['Home 08','Viveda / Anukor','knowledge']];
 @override void dispose(){pulse.dispose();super.dispose();}
 @override Widget build(BuildContext context){final t=CriterivoxTheme.of(context);final active=Set<String>.from(((widget.state?['active_homes']) as List?)?.map((e)=>e.toString())??const []);return LayoutBuilder(builder:(c,k){final size=math.min(k.maxWidth,760.0);final h=size*.86;return SizedBox(width:size,height:h,child:Stack(alignment:Alignment.center,children:[AnimatedBuilder(animation:pulse,builder:(_,__)=>CustomPaint(size:Size(size,h),painter:_VinePainter(active:active,pulse:pulse.value))),Container(width:size*.25,height:size*.25,decoration:BoxDecoration(shape:BoxShape.circle,gradient:RadialGradient(colors:[t.primary.withValues(alpha:.58),t.surfaceStrong,t.page]),border:Border.all(color:t.primary,width:2),boxShadow:[BoxShadow(color:t.primary.withValues(alpha:.24),blurRadius:34+pulse.value*14,spreadRadius:5)]),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text('🌸',style:TextStyle(fontSize:size*.045)),Text('THE BLOOM',style:TextStyle(color:t.text,fontWeight:FontWeight.w800,fontSize:12)),Text('${active.length} ACTIVE',style:TextStyle(color:t.mutedText,fontSize:8))])),..._petals(t,size,h)]);});}
 List<Widget> _petals(CriterivoxTheme t,double size,double h){final out=<Widget>[];final radius=size*.32;for(int i=0;i<homes.length;i++){final x=size/2+math.cos(-math.pi/2+i*2*math.pi/homes.length)*radius;final y=h/2+math.sin(-math.pi/2+i*2*math.pi/homes.length)*radius;final home=homes[i];final active=((widget.state?['active_homes']) as List?)?.map((e)=>e.toString()).contains(home[0])??false;out.add(Positioned(left:x-58,top:y-58,child:Tooltip(message:'Open ${home[0]} · ${home[1]}',child:InkWell(borderRadius:BorderRadius.circular(60),onTap:()=>widget.onOpen(home[2]),child:AnimatedContainer(duration:const Duration(milliseconds:240),width:116,height:116,decoration:BoxDecoration(shape:BoxShape.circle,gradient:RadialGradient(colors:[t.primary.withValues(alpha:active?.32:.10),t.surfaceStrong]),border:Border.all(color:t.primary.withValues(alpha:active?1:.42),width:active?2.2:1),boxShadow:[BoxShadow(color:t.primary.withValues(alpha:active?.32:.08),blurRadius:active?28:15,spreadRadius:active?4:1)]),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(Icons.local_florist_rounded,color:t.primary,size:22),Text(home[0],style:TextStyle(color:t.text,fontWeight:FontWeight.w800,fontSize:10)),Text(home[1],textAlign:TextAlign.center,style:TextStyle(color:t.mutedText,fontSize:8)),Text(active?'ACTIVE':'READY',style:TextStyle(color:t.primary,fontSize:7,fontWeight:FontWeight.w700))]))))));}return out;}
}
class _VinePainter extends CustomPainter{final Set<String> active;final double pulse;_VinePainter({required this.active,required this.pulse});@override void paint(Canvas c,Size s){final center=Offset(s.width/2,s.height*.5);final r=s.width*.32;for(int i=0;i<8;i++){final a=-math.pi/2+i*2*math.pi/8;final p=center+Offset(math.cos(a)*r,math.sin(a)*r);final key='Home ${(i+1).toString().padLeft(2,'0')}';c.drawLine(center,p,Paint()..color=Colors.white.withValues(alpha:.08+(active.contains(key)?.18:0))..strokeWidth=active.contains(key)?2:1);c.drawCircle(p,3+pulse*2,Paint()..color=Colors.white.withValues(alpha:.5));}}@override bool shouldRepaint(covariant _VinePainter old)=>old.pulse!=pulse||old.active!=active;}
